# mutation name used for import

mutation setRecipePreferencesForUser ($preferencesInput: RecipePreferencesInput!) {
    setRecipePreferencesForUser ( preferences: $preferencesInput )
    {
        vegan
        vegetarian
        gluten
        dairy
        cookingTime
    }
}
