# mutation name used for import

mutation setRecipePreferencesForUser ($preferencesInput: RecipePreferencesInput!) {
    setRecipePreferencesForUser ( preferences: $preferencesInput )
    {
        vegetarian
        vegan
        glutenfree
        lactosefree
        cookingTime
    }
}
